CREATE TABLE Users (
	ID INT UNSIGNED AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	Nickname VARCHAR(50),
	Birth_Date	DATE,
	Email VARCHAR(50) NOT NULL,
	Password_Hash VARCHAR(50) NOT NULL,
	Avatar VARCHAR(100),
	Description VARCHAR(100),
	CONSTRAINT PK_Users PRIMARY KEY (ID),
	CONSTRAINT U_Users_Email_Pasword UNIQUE (Email, Password_Hash)
);

CREATE TABLE Teams (
	ID INT UNSIGNED AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
	ID_Captain INT UNSIGNED NOT NULL,
	ID_Manager INT,
	CONSTRAINT PK_Teams PRIMARY KEY (ID),
	CONSTRAINT FK_Teams_Captain FOREIGN KEY (ID_Captain) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT U_Teams_Name UNIQUE (Name),
	CONSTRAINT U_Teams_ID_Captain UNIQUE (ID_Captain)
);